module.exports = {
  drafts: false,
  images: true,
  frontMatter: true,
  inputPath: '/Users/bdfinst/Downloads/posts',
  outputPath: 'src/blog-posts',
  imagePath: 'static/media',
  headingStyle: 'atx',
  hr: '---',
  bulletListMarker: '*',
  codeBlockStyle: 'fenced',
  fence: '```',
  emDelimiter: '_',
  strongDelimiter: '**',
  linkStyle: 'inlined',
  linkReferenceStyle: 'full',
}
